version: '3.9'

services:
  db:
    ports:
      - "3333:3306"
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: PASSpass1234
      MYSQL_USER: master
      MYSQL_PASSWORD: PASSpass1234
      MYSQL_DATABASE: kikwek
    volumes:
      - db-kikwek:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -pPASSpass1234"]
      interval: 2s
      timeout: 3s
      retries: 40

volumes:
  db-kikwek:
    name: kikweek
